In [0]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [0]:
iris = load_iris()

In [0]:
iris


{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [0]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
5                  5.4               3.9  ...               0.4       0
6                  4.6               3.4  ...               0.3       0
7                  5.0               3.4  ...               0.2       0
8                  4.4               2.9  ...               0.2       0
9                  4.9               3.1  ...               0.1       0
10                 5.4               3.7  ...               0.2       0
11                 4.8               3.4  ...               0.2       0
12                 4.8               3.0  ...               0.1       0
13                 4.3               3.0  ...               0.1       0
14                 5.8               4.0  ...               0.2       0
15                 5.7               4.4  ...               0.4       0
16                 5.4               3.9  ...               0.4       0
17                 5.1               3.5  ...               0.3       0
18                 5.7               3.8  ...               0.3       0
19                 5.1               3.8  ...               0.3       0
20                 5.4               3.4  ...               0.2       0
21                 5.1               3.7  ...               0.4       0
22                 4.6               3.6  ...               0.2       0
23                 5.1               3.3  ...               0.5       0
24                 4.8               3.4  ...               0.2       0
25                 5.0               3.0  ...               0.2       0
26                 5.0               3.4  ...               0.4       0
27                 5.2               3.5  ...               0.2       0
28                 5.2               3.4  ...               0.2       0
29                 4.7               3.2  ...               0.2       0
..                 ...               ...  ...               ...     ...
120                6.9               3.2  ...               2.3       2
121                5.6               2.8  ...               2.0       2
122                7.7               2.8  ...               2.0       2
123                6.3               2.7  ...               1.8       2
124                6.7               3.3  ...               2.1       2
125                7.2               3.2  ...               1.8       2
126                6.2               2.8  ...               1.8       2
127                6.1               3.0  ...               1.8       2
128                6.4               2.8  ...               2.1       2
129                7.2               3.0  ...               1.6       2
130                7.4               2.8  ...               1.9       2
131                7.9               3.8  ...               2.0       2
132                6.4               2.8  ...               2.2       2
133                6.3               2.8  ...               1.5       2
134                6.1               2.6  ...               1.4       2
135                7.7               3.0  ...               2.3       2
136                6.3               3.4  ...               2.4       2
137                6.4               3.1  ...               1.8       2
138                6.0               3.0  ...               1.8       2
139                6.9               3.1  ...               2.1       2
140                6.7               3.1  ...               2.4       2
141                6.9               3.1  ...               2.3       2
142                5.8               2.7  ...               1.9       2
143                6.8               3.2  ...

In [0]:
x = iris.data[50:,2].reshape(-1,1)
y = iris.target[50:] - 1

In [0]:
x


array([[4.7],
       [4.5],
       [4.9],
       [4. ],
       [4.6],
       [4.5],
       [4.7],
       [3.3],
       [4.6],
       [3.9],
       [3.5],
       [4.2],
       [4. ],
       [4.7],
       [3.6],
       [4.4],
       [4.5],
       [4.1],
       [4.5],
       [3.9],
       [4.8],
       [4. ],
       [4.9],
       [4.7],
       [4.3],
       [4.4],
       [4.8],
       [5. ],
       [4.5],
       [3.5],
       [3.8],
       [3.7],
       [3.9],
       [5.1],
       [4.5],
       [4.5],
       [4.7],
       [4.4],
       [4.1],
       [4. ],
       [4.4],
       [4.6],
       [4. ],
       [3.3],
       [4.2],
       [4.2],
       [4.2],
       [4.3],
       [3. ],
       [4.1],
       [6. ],
       [5.1],
       [5.9],
       [5.6],
       [5.8],
       [6.6],
       [4.5],
       [6.3],
       [5.8],
       [6.1],
       [5.1],
       [5.3],
       [5.5],
       [5. ],
       [5.1],
       [5.3],
       [5.5],
       [6.7],
       [6.9],
       [5. ],
       [5.7],
      

In [0]:
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
# ロジステック回帰実装
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [0]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [0]:
X_scaled

array([[-0.25077906],
       [-0.49425387],
       [-0.00730424],
       [-1.10294091],
       [-0.37251647],
       [-0.49425387],
       [-0.25077906],
       [-1.95510276],
       [-0.37251647],
       [-1.22467832],
       [-1.71162795],
       [-0.8594661 ],
       [-1.10294091],
       [-0.25077906],
       [-1.58989054],
       [-0.61599128],
       [-0.49425387],
       [-0.9812035 ],
       [-0.49425387],
       [-1.22467832],
       [-0.12904165],
       [-1.10294091],
       [-0.00730424],
       [-0.25077906],
       [-0.73772869],
       [-0.61599128],
       [-0.12904165],
       [ 0.11443316],
       [-0.49425387],
       [-1.71162795],
       [-1.34641572],
       [-1.46815313],
       [-1.22467832],
       [ 0.23617057],
       [-0.49425387],
       [-0.49425387],
       [-0.25077906],
       [-0.61599128],
       [-0.9812035 ],
       [-1.10294091],
       [-0.61599128],
       [-0.37251647],
       [-1.10294091],
       [-1.95510276],
       [-0.8594661 ],
       [-0

In [0]:
x_train,x_test,y_train,y_test = train_test_split(X_scaled,y,random_state=0)

In [0]:
log_reg = LogisticRegression().fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [0]:
log_reg.intercept_, log_reg.coef_

(array([0.26459322]), array([[3.15196557]]))

In [0]:
print(log_reg.score(x_train,y_train))
print(log_reg.score(x_test,y_test))

0.9466666666666667
0.88
